name: Publish phosphobot to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read
  # IMPORTANT: this permission is mandatory for Trusted Publishing
  id-token: write

jobs:
  publish_phospho_python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phosphobot

    steps:
      - uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "23.5"

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: phosphobot/dashboard

      - name: Build dashboard frontend
        env:
          VITE_SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: make build_frontend

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
