name: Publish phosphobot to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read
  # IMPORTANT: this permission is mandatory for Trusted Publishing
  id-token: write

jobs:
  publish_phospho_python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phosphobot

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
